export const ingredientOptions = [
  "Spicy Pepper",
  "Hyrule Bass",
  "Raw Meat",
  "Staminoka Bass",
  "Mighty Carp",
  "Fortified Pumpkin",
  "Blue Nightshade",
  "Hyrule Herb",
  "Silent Princess",
  "Apple",
  "Palm Fruit",
  "Wildberry",
  "Hylian Shroom",
  "Goron Spice",
  "Bird Egg",
  "Fresh Milk",
  "Goat Butter",
  "Crab",
  "Razorclaw Crab",
  "Hylian Rice",
  "Acorn",
  "Chickaloo Tree Nut",
  "Sugar",
  "Courser Bee Honey",
  "Salt",
  "Voltfruit",
  "Hearty Radish",
  "Ironshroom",
  "Armored Carp",
  "Hearty Blueshell Snail",
  "Mighty Porgy",
  "Endura Carrot",
  "Tabantha Wheat",
  "Cane Sugar",
  "Energetic Rhino Beetle",
  "Big Hearty Radish",
  "Hearty Salmon",
  "Rock Salt",
  "Cool Safflina",
  "Bright-Eyed Crab",
  "Sunshroom",
  "Big Hearty Truffle",
  "Swift Violet",
  "Sanke Carp",
  "Swift Carrot",
  "Zapshroom",
  "Armored Porgy",
  "Hearty Lizard",
  "Mighty Thistle",
  "Ironshell Crab",
  "Endura Shroom",
  "Mighty Bananas",
  "Hearty Durian",
  "Fleet-Lotus Seeds",
  "Hightail Lizard",
];
